LIST P = 16F887  
#include "p16f887.inc"

    __CONFIG _CONFIG1, _FOSC_EXTRC_CLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON

    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF


