LIST P=16F887  
#include "p16f887.inc"

    __CONFIG _CONFIG1, _FOSC_EXTRC_NOCLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_OFF
    __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    
    AUX EQU 0X20
    ORG	0X00
    GOTO INICIO
    ORG	0X04
    GOTO INT
    
INICIO
    BANKSEL TRISA
    BSF	TRISA, 0
    BSF	TRISA, 3
    BANKSEL ANSEL
    BSF	ANSEL, 3
    MOVLW   B'11000000'
    MOVWF INTCON
    BANKSEL PORTB
    CLRF AUX
    CLRF PORTB
    BANKSEL CM1CON0
    BSF	CM1CON0, 7
    BANKSEL TRISB   
    CLRF    TRISB
    BANKSEL PIE2
    MOVLW   B'00100000'
    MOVWF   PIE2
    GOTO    LOOP
    


LOOP
   BANKSEL CM1CON0
   MOVF    CM1CON0, 0
   BANKSEL PORTB
   MOVF	AUX,0
   MOVWF   PORTB
   GOTO LOOP
    
INT
   
    BANKSEL PIR2
    BTFSS   PIR2, 5
    RETFIE
    BANKSEL PORTB
    INCF    AUX, F
    BANKSEL PIR2
    BCF	PIR2, 5
    RETFIE
END